on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    name: Build ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: Windows x86_64
            runner: windows-latest
            triple: x86_64-pc-windows-msvc
          - os: Windows i686
            runner: windows-latest
            triple: i686-pc-windows-msvc
          - os: Linux musl
            runner: ubuntu-latest
            triple: x86_64-unknown-linux-musl
          - os: MacOS ARM
            runner: macos-latest
            triple: aarch64-apple-darwin
          - os: MacOS x86_64
            runner: macos-latest
            triple: x86_64-apple-darwin
    runs-on: ${{ matrix.target.runner }}
    steps:
    - uses: actions/checkout@v4
    - name: Install nightly rust toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        target: ${{ matrix.target.triple }}
        default: true
        override: true
    - name: Compile
      run: cargo build --release --bin blazectl
    - name: Cache rust artifacts
      uses: Swatinem/rust-cache@v2
    - name: Upload artifact
      if: ${{ matrix.target.runner == 'windows-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: blaze-${{ matrix.target.triple }}
        path: target/${{ matrix.target.triple }}/release/blazectl.exe
    - name: Upload artifact
      if: ${{ matrix.target.runner != 'windows-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: blaze-${{ matrix.target.triple }}
        path: target/${{matrix.target.triple }}/release/blazectl
