on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      targets:
        description: 'Targets to run the compiler for'
        required: true
        default: 'linux'
        type: choice
        options:
          - linux
          - windows
          - mac
          - all

jobs:
  # Thanks https://stackoverflow.com/questions/65384420/how-do-i-make-a-github-action-matrix-element-conditional
  gen-matrix:
    name: Generate build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        uses: JoshuaTheMiller/conditional-build-matrix@main
        with:
          filter: |
            [?(
              '${{ github.event_name }}' == 'push' ||
              '${{ github.event.inputs.targets }}' == 'all' ||
              '${{ github.event.inputs.targets }}' == tag
            )]
      - name: Debug
        run: |
          echo 'Generated matrix:'
          echo ${{ steps.set.outputs.matrix }}

  build:
    needs: gen-matrix
    name: Build ${{ matrix.target.os }}
    runs-on: ${{ matrix.target.runner }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.gen-matrix.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4
    - name: Install nightly rust toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        # Pin toolchain version for better caching
        toolchain: nightly-2025-01-26
        target: ${{ matrix.target.triple }}
        default: true
        override: true
    - name: Restore cached rust artifacts
      uses: Swatinem/rust-cache@v2
    - name: Compile
      run: cargo build --release --bin blazectl
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: blaze-${{ matrix.target.triple }}
        path: target/release/blazectl*
